language: minimal
branches:
  only:
    - master
deploy:
    region: eu-west-1
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: static.grange85.co.uk
    skip_cleanup: true
    local-dir: deploy
    upload_dir: geoproject
    acl: public_read
    detect_encoding: true
notifications:
    email:
on_failure: always
