language: minimal
branches:
  only:
    - master
before_deploy:
    openssl aes-256-cbc -K $encrypted_30cd4b4f51ed_key -iv $encrypted_30cd4b4f51ed_iv -in s3cfg-prod.enc -out s3cfg-prod -d
deploy:
    region: us-east-1
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: static.fullofwishes.co.uk
    skip_cleanup: true
    local-dir: deploy
    upload_dir: geoproject
    acl: public_read
    detect_encoding: true
notifications:
    email:
on_failure: always
before_deploy: 
  - pip install --user awscli
after_deploy:
    aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
